jwt:
  secret: my-super-secret-jwt-key-my-super-secret-jwt-key-2026
  access-token-expiration: 3600000  # 1시간

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project01?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 2937

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format_sql: true

  thymeleaf:
    cache: false
